export const countries = [
  { name: 'Afganistán', native: 'افغانستان', code: 'AF', dialCode: '+93' },
  { name: 'Albania', native: 'Shqipëria', code: 'AL', dialCode: '+355' },
  { name: 'Alemania', native: 'Deutschland', code: 'DE', dialCode: '+49' },
  { name: 'Andorra', native: 'Andorra', code: 'AD', dialCode: '+376' },
  { name: 'Angola', native: 'Angola', code: 'AO', dialCode: '+244' },
  { name: 'Arabia Saudita', native: 'العربية السعودية', code: 'SA', dialCode: '+966' },
  { name: 'Argelia', native: 'الجزائر', code: 'DZ', dialCode: '+213' },
  { name: 'Argentina', native: 'Argentina', code: 'AR', dialCode: '+54' },
  { name: 'Armenia', native: 'Հայաստան', code: 'AM', dialCode: '+374' },
  { name: 'Australia', native: 'Australia', code: 'AU', dialCode: '+61' },
  { name: 'Austria', native: 'Österreich', code: 'AT', dialCode: '+43' },
  { name: 'Azerbaiyán', native: 'Azərbaycan', code: 'AZ', dialCode: '+994' },
  { name: 'Bahamas', native: 'Bahamas', code: 'BS', dialCode: '+1' },
  { name: 'Bangladés', native: 'বাংলাদেশ', code: 'BD', dialCode: '+880' },
  { name: 'Bélgica', native: 'België', code: 'BE', dialCode: '+32' },
  { name: 'Belice', native: 'Belize', code: 'BZ', dialCode: '+501' },
  { name: 'Benín', native: 'Bénin', code: 'BJ', dialCode: '+229' },
  { name: 'Bielorrusia', native: 'Беларусь', code: 'BY', dialCode: '+375' },
  { name: 'Bolivia', native: 'Bolivia', code: 'BO', dialCode: '+591' },
  { name: 'Bosnia y Herzegovina', native: 'Bosna i Hercegovina', code: 'BA', dialCode: '+387' },
  { name: 'Botsuana', native: 'Botswana', code: 'BW', dialCode: '+267' },
  { name: 'Brasil', native: 'Brasil', code: 'BR', dialCode: '+55' },
  { name: 'Bulgaria', native: 'България', code: 'BG', dialCode: '+359' },
  { name: 'Camboya', native: 'កម្ពុជា', code: 'KH', dialCode: '+855' },
  { name: 'Camerún', native: 'Cameroun', code: 'CM', dialCode: '+237' },
  { name: 'Canadá', native: 'Canada', code: 'CA', dialCode: '+1' },
  { name: 'Catar', native: 'قطر', code: 'QA', dialCode: '+974' },
  { name: 'Chile', native: 'Chile', code: 'CL', dialCode: '+56' },
  { name: 'China', native: '中国', code: 'CN', dialCode: '+86' },
  { name: 'Chipre', native: 'Κύπρος', code: 'CY', dialCode: '+357' },
  { name: 'Colombia', native: 'Colombia', code: 'CO', dialCode: '+57' },
  { name: 'Corea del Sur', native: '대한민국', code: 'KR', dialCode: '+82' },
  { name: 'Costa Rica', native: 'Costa Rica', code: 'CR', dialCode: '+506' },
  { name: 'Croacia', native: 'Hrvatska', code: 'HR', dialCode: '+385' },
  { name: 'Cuba', native: 'Cuba', code: 'CU', dialCode: '+53' },
  { name: 'Dinamarca', native: 'Danmark', code: 'DK', dialCode: '+45' },
  { name: 'Ecuador', native: 'Ecuador', code: 'EC', dialCode: '+593' },
  { name: 'Egipto', native: 'مصر', code: 'EG', dialCode: '+20' },
  { name: 'El Salvador', native: 'El Salvador', code: 'SV', dialCode: '+503' },
  { name: 'Emiratos Árabes Unidos', native: 'الإمارات العربية المتحدة', code: 'AE', dialCode: '+971' },
  { name: 'Eslovaquia', native: 'Slovensko', code: 'SK', dialCode: '+421' },
  { name: 'Eslovenia', native: 'Slovenija', code: 'SI', dialCode: '+386' },
  { name: 'España', native: 'España', code: 'ES', dialCode: '+34' },
  { name: 'Estados Unidos', native: 'United States', code: 'US', dialCode: '+1' },
  { name: 'Estonia', native: 'Eesti', code: 'EE', dialCode: '+372' },
  { name: 'Etiopía', native: 'ኢትዮጵያ', code: 'ET', dialCode: '+251' },
  { name: 'Filipinas', native: 'Pilipinas', code: 'PH', dialCode: '+63' },
  { name: 'Finlandia', native: 'Suomi', code: 'FI', dialCode: '+358' },
  { name: 'Francia', native: 'France', code: 'FR', dialCode: '+33' },
  { name: 'Georgia', native: 'საქართველო', code: 'GE', dialCode: '+995' },
  { name: 'Ghana', native: 'Ghana', code: 'GH', dialCode: '+233' },
  { name: 'Grecia', native: 'Ελλάδα', code: 'GR', dialCode: '+30' },
  { name: 'Guatemala', native: 'Guatemala', code: 'GT', dialCode: '+502' },
  { name: 'Haití', native: 'Haïti', code: 'HT', dialCode: '+509' },
  { name: 'Honduras', native: 'Honduras', code: 'HN', dialCode: '+504' },
  { name: 'Hong Kong', native: '香港', code: 'HK', dialCode: '+852' },
  { name: 'Hungría', native: 'Magyarország', code: 'HU', dialCode: '+36' },
  { name: 'India', native: 'भारत', code: 'IN', dialCode: '+91' },
  { name: 'Indonesia', native: 'Indonesia', code: 'ID', dialCode: '+62' },
  { name: 'Irak', native: 'العراق', code: 'IQ', dialCode: '+964' },
  { name: 'Irán', native: 'ایران', code: 'IR', dialCode: '+98' },
  { name: 'Irlanda', native: 'Éire', code: 'IE', dialCode: '+353' },
  { name: 'Islandia', native: 'Ísland', code: 'IS', dialCode: '+354' },
  { name: 'Israel', native: 'ישראל', code: 'IL', dialCode: '+972' },
  { name: 'Italia', native: 'Italia', code: 'IT', dialCode: '+39' },
  { name: 'Jamaica', native: 'Jamaica', code: 'JM', dialCode: '+1' },
  { name: 'Japón', native: '日本', code: 'JP', dialCode: '+81' },
  { name: 'Jordania', native: 'الأردن', code: 'JO', dialCode: '+962' },
  { name: 'Kazajstán', native: 'Қазақстан', code: 'KZ', dialCode: '+7' },
  { name: 'Kenia', native: 'Kenya', code: 'KE', dialCode: '+254' },
  { name: 'Kirguistán', native: 'Кыргызстан', code: 'KG', dialCode: '+996' },
  { name: 'Kuwait', native: 'الكويت', code: 'KW', dialCode: '+965' },
  { name: 'Letonia', native: 'Latvija', code: 'LV', dialCode: '+371' },
  { name: 'Líbano', native: 'لبنان', code: 'LB', dialCode: '+961' },
  { name: 'Libia', native: 'ليبيا', code: 'LY', dialCode: '+218' },
  { name: 'Lituania', native: 'Lietuva', code: 'LT', dialCode: '+370' },
  { name: 'Luxemburgo', native: 'Lëtzebuerg', code: 'LU', dialCode: '+352' },
  { name: 'Macao', native: '澳門', code: 'MO', dialCode: '+853' },
  { name: 'Macedonia del Norte', native: 'Северна Македонија', code: 'MK', dialCode: '+389' },
  { name: 'Madagascar', native: 'Madagasikara', code: 'MG', dialCode: '+261' },
  { name: 'Malasia', native: 'Malaysia', code: 'MY', dialCode: '+60' },
  { name: 'Malta', native: 'Malta', code: 'MT', dialCode: '+356' },
  { name: 'Marruecos', native: 'المغرب', code: 'MA', dialCode: '+212' },
  { name: 'México', native: 'México', code: 'MX', dialCode: '+52' },
  { name: 'Moldavia', native: 'Moldova', code: 'MD', dialCode: '+373' },
  { name: 'Mónaco', native: 'Monaco', code: 'MC', dialCode: '+377' },
  { name: 'Mongolia', native: 'Монгол улс', code: 'MN', dialCode: '+976' },
  { name: 'Montenegro', native: 'Crna Gora', code: 'ME', dialCode: '+382' },
  { name: 'Mozambique', native: 'Moçambique', code: 'MZ', dialCode: '+258' },
  { name: 'Myanmar', native: 'မြန်မာ', code: 'MM', dialCode: '+95' },
  { name: 'Namibia', native: 'Namibia', code: 'NA', dialCode: '+264' },
  { name: 'Nepal', native: 'नेपाल', code: 'NP', dialCode: '+977' },
  { name: 'Nicaragua', native: 'Nicaragua', code: 'NI', dialCode: '+505' },
  { name: 'Níger', native: 'Niger', code: 'NE', dialCode: '+227' },
  { name: 'Nigeria', native: 'Nigeria', code: 'NG', dialCode: '+234' },
  { name: 'Noruega', native: 'Norge', code: 'NO', dialCode: '+47' },
  { name: 'Nueva Zelanda', native: 'New Zealand', code: 'NZ', dialCode: '+64' },
  { name: 'Omán', native: 'عمان', code: 'OM', dialCode: '+968' },
  { name: 'Países Bajos', native: 'Nederland', code: 'NL', dialCode: '+31' },
  { name: 'Pakistán', native: 'پاکستان', code: 'PK', dialCode: '+92' },
  { name: 'Panamá', native: 'Panamá', code: 'PA', dialCode: '+507' },
  { name: 'Paraguay', native: 'Paraguay', code: 'PY', dialCode: '+595' },
  { name: 'Perú', native: 'Perú', code: 'PE', dialCode: '+51' },
  { name: 'Polonia', native: 'Polska', code: 'PL', dialCode: '+48' },
  { name: 'Portugal', native: 'Portugal', code: 'PT', dialCode: '+351' },
  { name: 'Reino Unido', native: 'United Kingdom', code: 'GB', dialCode: '+44' },
  { name: 'República Checa', native: 'Česko', code: 'CZ', dialCode: '+420' },
  { name: 'República Dominicana', native: 'República Dominicana', code: 'DO', dialCode: '+1' },
  { name: 'Rumania', native: 'România', code: 'RO', dialCode: '+40' },
  { name: 'Rusia', native: 'Россия', code: 'RU', dialCode: '+7' },
  { name: 'Senegal', native: 'Sénégal', code: 'SN', dialCode: '+221' },
  { name: 'Serbia', native: 'Србија', code: 'RS', dialCode: '+381' },
  { name: 'Singapur', native: 'Singapore', code: 'SG', dialCode: '+65' },
  { name: 'Siria', native: 'سوريا', code: 'SY', dialCode: '+963' },
  { name: 'Sri Lanka', native: 'ශ්‍රී ලංකාව', code: 'LK', dialCode: '+94' },
  { name: 'Sudáfrica', native: 'South Africa', code: 'ZA', dialCode: '+27' },
  { name: 'Suecia', native: 'Sverige', code: 'SE', dialCode: '+46' },
  { name: 'Suiza', native: 'Schweiz', code: 'CH', dialCode: '+41' },
  { name: 'Tailandia', native: 'ประเทศไทย', code: 'TH', dialCode: '+66' },
  { name: 'Taiwán', native: '台灣', code: 'TW', dialCode: '+886' },
  { name: 'Tanzania', native: 'Tanzania', code: 'TZ', dialCode: '+255' },
  { name: 'Tayikistán', native: 'Тоҷикистон', code: 'TJ', dialCode: '+992' },
  { name: 'Túnez', native: 'تونس', code: 'TN', dialCode: '+216' },
  { name: 'Turquía', native: 'Türkiye', code: 'TR', dialCode: '+90' },
  { name: 'Turkmenistán', native: 'Türkmenistan', code: 'TM', dialCode: '+993' },
  { name: 'Ucrania', native: 'Україна', code: 'UA', dialCode: '+380' },
  { name: 'Uganda', native: 'Uganda', code: 'UG', dialCode: '+256' },
  { name: 'Uruguay', native: 'Uruguay', code: 'UY', dialCode: '+598' },
  { name: 'Uzbekistán', native: 'Oʻzbekiston', code: 'UZ', dialCode: '+998' },
  { name: 'Venezuela', native: 'Venezuela', code: 'VE', dialCode: '+58' },
  { name: 'Vietnam', native: 'Việt Nam', code: 'VN', dialCode: '+84' },
].sort((a, b) => {
  const codeA = parseInt(a.dialCode.replace('+', ''));
  const codeB = parseInt(b.dialCode.replace('+', ''));
  if (codeA !== codeB) return codeA - codeB;
  return a.native.localeCompare(b.native);
});
